// Code generated by MockGen. DO NOT EDIT.
// Source: meta_storage.go

// Package mocks is a generated GoMock package.
package mocks

import (
	models "Proteus/internal/models"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMetaStorage is a mock of MetaStorage interface.
type MockMetaStorage struct {
	ctrl     *gomock.Controller
	recorder *MockMetaStorageMockRecorder
}

// MockMetaStorageMockRecorder is the mock recorder for MockMetaStorage.
type MockMetaStorageMockRecorder struct {
	mock *MockMetaStorage
}

// NewMockMetaStorage creates a new mock instance.
func NewMockMetaStorage(ctrl *gomock.Controller) *MockMetaStorage {
	mock := &MockMetaStorage{ctrl: ctrl}
	mock.recorder = &MockMetaStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetaStorage) EXPECT() *MockMetaStorageMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockMetaStorage) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockMetaStorageMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockMetaStorage)(nil).Close))
}

// DeleteBatch mocks base method.
func (m *MockMetaStorage) DeleteBatch(ctx context.Context, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBatch", ctx, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBatch indicates an expected call of DeleteBatch.
func (mr *MockMetaStorageMockRecorder) DeleteBatch(ctx, ids interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBatch", reflect.TypeOf((*MockMetaStorage)(nil).DeleteBatch), ctx, ids)
}

// GetDeleted mocks base method.
func (m *MockMetaStorage) GetDeleted(ctx context.Context) ([]models.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeleted", ctx)
	ret0, _ := ret[0].([]models.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeleted indicates an expected call of GetDeleted.
func (mr *MockMetaStorageMockRecorder) GetDeleted(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeleted", reflect.TypeOf((*MockMetaStorage)(nil).GetDeleted), ctx)
}

// GetImageMeta mocks base method.
func (m *MockMetaStorage) GetImageMeta(ctx context.Context, id string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetImageMeta", ctx, id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetImageMeta indicates an expected call of GetImageMeta.
func (mr *MockMetaStorageMockRecorder) GetImageMeta(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetImageMeta", reflect.TypeOf((*MockMetaStorage)(nil).GetImageMeta), ctx, id)
}

// MarkAsDeleted mocks base method.
func (m *MockMetaStorage) MarkAsDeleted(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsDeleted", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsDeleted indicates an expected call of MarkAsDeleted.
func (mr *MockMetaStorageMockRecorder) MarkAsDeleted(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsDeleted", reflect.TypeOf((*MockMetaStorage)(nil).MarkAsDeleted), ctx, id)
}

// MarkAsReady mocks base method.
func (m *MockMetaStorage) MarkAsReady(ctx context.Context, objectKey, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsReady", ctx, objectKey, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsReady indicates an expected call of MarkAsReady.
func (mr *MockMetaStorageMockRecorder) MarkAsReady(ctx, objectKey, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsReady", reflect.TypeOf((*MockMetaStorage)(nil).MarkAsReady), ctx, objectKey, id)
}

// SaveImageMeta mocks base method.
func (m *MockMetaStorage) SaveImageMeta(ctx context.Context, image *models.Image) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveImageMeta", ctx, image)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveImageMeta indicates an expected call of SaveImageMeta.
func (mr *MockMetaStorageMockRecorder) SaveImageMeta(ctx, image interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveImageMeta", reflect.TypeOf((*MockMetaStorage)(nil).SaveImageMeta), ctx, image)
}
