// Code generated by MockGen. DO NOT EDIT.
// Source: service.go

// Package mocks is a generated GoMock package.
package mocks

import (
	models "Proteus/internal/models"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// Cleaner mocks base method.
func (m *MockService) Cleaner(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Cleaner", ctx)
}

// Cleaner indicates an expected call of Cleaner.
func (mr *MockServiceMockRecorder) Cleaner(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cleaner", reflect.TypeOf((*MockService)(nil).Cleaner), ctx)
}

// DownloadImage mocks base method.
func (m *MockService) DownloadImage(ctx context.Context, key string) ([]byte, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DownloadImage", ctx, key)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DownloadImage indicates an expected call of DownloadImage.
func (mr *MockServiceMockRecorder) DownloadImage(ctx, key interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DownloadImage", reflect.TypeOf((*MockService)(nil).DownloadImage), ctx, key)
}

// GetImageMeta mocks base method.
func (m *MockService) GetImageMeta(ctx context.Context, id string) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetImageMeta", ctx, id)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetImageMeta indicates an expected call of GetImageMeta.
func (mr *MockServiceMockRecorder) GetImageMeta(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetImageMeta", reflect.TypeOf((*MockService)(nil).GetImageMeta), ctx, id)
}

// MarkAsDeleted mocks base method.
func (m *MockService) MarkAsDeleted(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsDeleted", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsDeleted indicates an expected call of MarkAsDeleted.
func (mr *MockServiceMockRecorder) MarkAsDeleted(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsDeleted", reflect.TypeOf((*MockService)(nil).MarkAsDeleted), ctx, id)
}

// ProcessImage mocks base method.
func (m *MockService) ProcessImage(ctx context.Context, task models.ImageProcessTask) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessImage", ctx, task)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessImage indicates an expected call of ProcessImage.
func (mr *MockServiceMockRecorder) ProcessImage(ctx, task interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessImage", reflect.TypeOf((*MockService)(nil).ProcessImage), ctx, task)
}

// UploadImage mocks base method.
func (m *MockService) UploadImage(ctx context.Context, image *models.Image) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadImage", ctx, image)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadImage indicates an expected call of UploadImage.
func (mr *MockServiceMockRecorder) UploadImage(ctx, image interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadImage", reflect.TypeOf((*MockService)(nil).UploadImage), ctx, image)
}
